apiVersion: apps/v1
kind: Deployment
metadata:
  name: drawguess-server-realtime
  namespace: default
  labels:
    app: drawguess-server-realtime
    version: v3.1.20250819-1827-0ea1d31
  annotations:
    # ArgoCD가 이 리소스를 관리함을 명시
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1 # 단일 노드이므로 1개로 시작
  selector:
    matchLabels:
      app: drawguess-server-realtime
  template:
    metadata:
      labels:
        app: drawguess-server-realtime
        version: v3.1.20250819-1827-0ea1d31
      annotations:
        # 설정 변경 시 Pod 재시작을 위한 체크섬 (수동으로 업데이트)
        config.checksum: "update-when-config-changes"
    spec:
      containers:
        - name: game-server
          image: 172.30.1.64:32000/drawguess/game-server:v3.1.20250819-1827-0ea1d31
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
          envFrom:
            - configMapRef:
                name: game-config
            - secretRef:
                name: db-credentials
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 5
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      securityContext:
        fsGroup: 1000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
