apiVersion: v1
kind: Service
metadata:
  name: drawguess-server-realtime
  namespace: default
  labels:
    app: drawguess-server-realtime
  annotations:
    # MetalLB 설정
    metallb.universe.tf/allow-shared-ip: "drawguess-game"
    # ArgoCD 동기화 설정
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: LoadBalancer
  loadBalancerIP: 172.30.1.102
  # Socket.IO WebSocket 연결 안정성을 위한 세션 유지
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3시간
  selector:
    app: drawguess-server-realtime
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  externalTrafficPolicy: Local