apiVersion: apps/v1
kind: Deployment
metadata:
  name: drawguess-server-realtime
  namespace: default
  labels:
    app: drawguess-server-realtime
    version: v3.1.0
    tier: backend
spec:
  replicas: 1  # 단일 노드이므로 1개로 시작
  selector:
    matchLabels:
      app: drawguess-server-realtime
  template:
    metadata:
      labels:
        app: drawguess-server-realtime
        version: v3.1.0
        tier: backend
    spec:
      containers:
      - name: game-server
        image: 172.30.1.64:32000/drawguess/game-server:v3.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        # Redis 설정
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: game-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: game-config
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: game-config
              key: REDIS_PASSWORD
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: game-config
              key: NODE_ENV
        # PostgreSQL 설정
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: drawguess-server-realtime
  namespace: default
  labels:
    app: drawguess-server-realtime
    version: v3.1.0
spec:
  type: LoadBalancer
  loadBalancerIP: 172.30.1.102
  # Socket.IO WebSocket 연결 안정성을 위한 세션 유지
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3시간
  selector:
    app: drawguess-server-realtime
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  externalTrafficPolicy: Local
