apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: drawguess-server-metrics
  namespace: monitoring
  labels:
    app: drawguess-server
    release: prometheus
spec:
  selector:
    matchLabels:
      app: drawguess-server-realtime
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - default