apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: drawguess-server-metrics
  namespace: monitoring
  labels:
    app: drawguess-server
    release: prometheus
spec:
  selector:
    matchLabels:
      app: drawguess-server-realtime
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - default
---
apiVersion: v1
kind: Service
metadata:
  name: drawguess-server-metrics
  namespace: default
  labels:
    app: drawguess-server-realtime
    metrics: prometheus
spec:
  selector:
    app: drawguess-server-realtime
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP